from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

def create_menu_ppt():
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "메뉴 구조 리포트"
    subtitle.text = "Database (Table) 정보 기반\nGenerated by Antigravity AI"

    # Menu Data Structure
    menus = [
        {"root": "Financial", "children": [
            {"name": "카드이력", "url": "/transactions", "icon": "CreditCard", "sort": 1},
            {"name": "Trade History", "url": "/trade-history", "icon": "Wallet", "sort": 3},
            {"name": "Trade Status", "url": "/coin-status", "icon": "LayoutDashboard", "sort": 4}
        ]},
        {"root": "Board", "children": [
            {"name": "공지사항", "url": "/notice", "icon": "Hash", "sort": 1},
            {"name": "갤러리", "url": "/gallery", "icon": "Image", "sort": 1},
            {"name": "갤러리 탐색기", "url": "/settings/image-explorer", "icon": "Image", "sort": 4}
        ]},
        {"root": "Settings", "children": [
            {"name": "Profile", "url": "/profile", "icon": "User", "sort": 1},
            {"name": "메뉴 관리", "url": "/settings/menu-management", "icon": "Circle", "sort": 2},
            {"name": "지도", "url": "/map", "icon": "Map", "sort": 3},
            {"name": "달력", "url": "/settings/calendar", "icon": "Calendar", "sort": 4},
            {"name": "관리자 관리", "url": "/admin", "icon": "Shield", "sort": 5},
            {"name": "휴일 관리", "url": "/holidays", "icon": "Calendar", "sort": 6}
        ]}
    ]

    # Overall Summary Slide
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "시스템 전체 메뉴 요약"
    
    rows = 16 # Title + 15 items
    cols = 4
    left = Inches(0.5)
    top = Inches(1.5)
    width = Inches(9.0)
    height = Inches(0.4)

    table = slide.shapes.add_table(rows, cols, left, top, width, height).table
    
    # Header
    table.cell(0, 0).text = "구분"
    table.cell(0, 1).text = "메뉴명"
    table.cell(0, 2).text = "URL"
    table.cell(0, 3).text = "정렬"

    row_idx = 1
    for root in menus:
        # Root row
        table.cell(row_idx, 0).text = root['root']
        table.cell(row_idx, 1).text = "-"
        table.cell(row_idx, 2).text = "-"
        table.cell(row_idx, 3).text = "-"
        row_idx += 1
        for child in root['children']:
            table.cell(row_idx, 0).text = ""
            table.cell(row_idx, 1).text = child['name']
            table.cell(row_idx, 2).text = child['url']
            table.cell(row_idx, 3).text = str(child['sort'])
            row_idx += 1

    # Individual slides for each root
    for root in menus:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = f"메뉴 상세: {root['root']}"
        
        # Add a table or bullet points
        content = slide.placeholders[1]
        tf = content.text_frame
        tf.text = f"{root['root']} 하위 메뉴:"
        
        for child in root['children']:
            p = tf.add_paragraph()
            p.text = f"• {child['name']} (URL: {child['url']}, Icon: {child['icon']})"
            p.level = 1

    # Save
    import os
    artifact_path = r"C:\Users\leele\.gemini\antigravity\brain\6165d268-e9fe-4062-80dd-f0c1e45b2e4b\menu_report.pptx"
    prs.save(artifact_path)
    print(f"PPTX saved to {artifact_path}")

if __name__ == "__main__":
    create_menu_ppt()
